services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - LLAMA_URL=http://host.docker.internal:8080/completion
      - CHROMA_PATH=/app/data/chroma_db
    volumes:
      - ./data:/app/data
      # deploy:
  # replicas: 3 # not needed rn
  # uncomment these when we need to scale this is taking too much time to build

  worker:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - LLAMA_URL=http://host.docker.internal:8080/completion
    volumes:
      - ./data:/app/data
    command: python worker.py
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
volumes:
  redis_data:
